name: Build Debug APK

on:
  push:
    branches:
      - main  # Change if needed

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Set up Node.js with Yarn cache
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      # Step 4: Setup Metro Config
      - name: Setup Metro Config
        run: |
          echo "Ensuring metro.config.js is set correctly..."
          cat <<EOT > metro.config.js
          const { getDefaultConfig } = require('@react-native/metro-config');
          module.exports = getDefaultConfig(__dirname);
          EOT

      # Step 5: Ensure Assets Directory Exists
      - name: Ensure Assets Directory Exists
        run: mkdir -p android/app/src/main/assets

      # Step 6: Cache Metro & Gradle
      - name: Cache Metro & Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.metro-cache
          key: ${{ runner.os }}-gradle-metro-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-gradle-metro-

      # Step 7: Bundle React Native JavaScript
      - name: Bundle React Native JavaScript
        run: |
          npx react-native start --reset-cache &
          npx react-native bundle --platform android --dev false \
          --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle \
          --assets-dest android/app/src/main/res/

      # Step 8: Debug - List res folder contents
      - name: List res folder contents
        run: ls -R android/app/src/main/res

      # Step 9: Clean Gradle Build
      - name: Clean Gradle Build
        run: cd android && ./gradlew clean

      # Step 10: Grant Execution Permission to Gradle
      - name: Grant Execution Permission to Gradle
        run: chmod +x android/gradlew

      # Step 11: Build Debug APK with Gradle
      - name: Build Debug APK with Gradle
        run: cd android && ./gradlew assembleDebug --no-daemon --stacktrace --info

      # Step 12: Verify Latest Commit Hash
      - name: Verify Latest Commit Hash
        run: echo "Latest commit hash: $(git rev-parse HEAD)"

      # Step 13: Ensure APK Exists
      - name: Ensure APK Exists
        run: |
          echo "Checking if APK exists..."
          ls -lah android/app/build/outputs/apk/debug/
        continue-on-error: true

      # Step 14: Upload APK as Artifact
      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-app
          path: android/app/build/outputs/apk/debug/app-debug.apk
