name: Build Release APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Setup Metro Config
        run: |
          cat <<EOT > metro.config.js
          const { getDefaultConfig } = require('@react-native/metro-config');
          module.exports = getDefaultConfig(__dirname);
          EOT

      - name: Create Assets Directory
        run: mkdir -p android/app/src/main/assets

      - name: Cache Gradle and Metro
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.metro-cache
          key: ${{ runner.os }}-gradle-metro-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-gradle-metro-

      - name: Bundle React Native JS (Release)
        run: |
          node ./node_modules/react-native/cli.js bundle \
            --platform android \
            --dev true \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res/ \
            --config metro.config.js

      - name: Clean Gradle
        run: cd android && ./gradlew clean

      - name: Make Gradle Executable
        run: chmod +x android/gradlew

      - name: Build Release APK (Verbose)
        run: |
          cd android
          ./gradlew assembleRelease \
            --stacktrace \
            --no-daemon \
            --console=plain \
            --warning-mode all

      - name: List APKs
        run: find android/app/build/outputs/apk -type f

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk-${{ github.sha }}
          path: android/app/build/outputs/apk/release/*.apk

      - name: Analyze Release APK Size
        run: |
          mkdir -p apk-release-extracted
          unzip -q android/app/build/outputs/apk/release/app-release.apk -d apk-release-extracted

          echo "=== Top-Level APK Contents ===" > apk-size-report.txt
          du -sh apk-release-extracted/* | sort -hr >> apk-size-report.txt

          echo "\n=== Top 20 Largest Files ===" >> apk-size-report.txt
          find apk-release-extracted -type f -exec du -h {} + | sort -hr | head -n 20 >> apk-size-report.txt

      - name: Upload APK Size Report
        uses: actions/upload-artifact@v4
        with:
          name: apk-size-report-${{ github.sha }}
          path: apk-size-report.txt

      - name: Dump DEX Class Details
        run: |
          mkdir -p dex-analysis
          unzip -q android/app/build/outputs/apk/release/app-release.apk -d dex-analysis/apk
          for dex in dex-analysis/apk/classes*.dex; do
            dexdump -a "$dex" > dex-analysis/$(basename "$dex").txt || echo "Failed to dump $dex"
          done

      - name: Upload DEX Class Dump
        uses: actions/upload-artifact@v4
        with:
          name: dex-class-report-${{ github.sha }}
          path: dex-analysis/*.txt

      - name: Dump Logs on Failure
        if: failure()
        run: find android -name "*.log" -exec cat {} \; || true
